services:
  
  mysql-proddb:
    image: mysql:latest
    container_name: mysql-proddb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prodDb
    networks:
      - backend
    ports:
      - "3306:3308"  # Expose MySQL on default port
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  mysql-auftdb:
    image: mysql:latest
    container_name: mysql-auftdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auftDb
    networks:
      - backend
    ports:
      - "3307:3306"  # Map MySQL container port 3306 to host port 3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  nginx-server:
    image: nginx:latest
    container_name: nginx-server
    depends_on:
      mysql-proddb:
        condition: service_healthy
      mysql-auftdb:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      mysql-proddb:
        condition: service_healthy
      mysql-auftdb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
  
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - "9091:9091"

networks:
  backend:
    driver: bridge
