services:
  
  mysql-proddb:
    image: mysql:latest
    container_name: mysql-proddb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prodDb
    networks:
      - proddb_net  # Unique network for this container
    ports:
      - "3306:3306"  # Expose on 3306 for mysql-proddb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  mysql-auftdb:
    image: mysql:latest
    container_name: mysql-auftdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auftDb
    networks:
      - auftdb_net  # Unique network for this container
    ports:
      - "3307:3306"  # Expose on 3307 for mysql-auftdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  nginx-server:
    image: nginx:latest
    container_name: nginx-server
    depends_on:
      mysql-proddb:
        condition: service_healthy
      mysql-auftdb:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - proddb_net
      - auftdb_net

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      mysql-proddb:
        condition: service_healthy
      mysql-auftdb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - proddb_net
      - auftdb_net
  
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - "9091:9091"

networks:
  proddb_net:
    driver: bridge
  auftdb_net:
    driver: bridge
